# Generated by Django 3.2.5 on 2022-01-12 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('venue', models.CharField(max_length=30)),
                ('crowdsize', models.IntegerField(default=50)),
                ('bookedsize', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('avg_ratings', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('num_of_ratings', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('O', 'OPEN_BOOKING'), ('C', 'BOOKINGS_CLOSED'), ('X', 'EVENT CANCELLED'), ('Y', 'EVENT_COMPLETE')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=4)),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_booking.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_booking.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booked_at', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_booking.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_booking.user')),
            ],
        ),
    ]
