# Generated by Django 3.2.5 on 2022-01-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='avg_ratings',
        ),
    ]
